---
# tasks file for python_dependencies

- name: Install python dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - python-dev
    - build-essential
    - python-setuptools
    - python-pip
  ignore_errors: yes
